Removed due to the following error. There was no file in /snippets/csdinstall.rst
/Users/ianbarker/documentation/docs/source/admin/installguide.rst:294: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'source/snippets/csdinstall.rst'.